### ISSUE TITLE
Maestral continues to crash in background

### ISSUE THREAD

**Issue by schwerd** [samschott/maestral#939]
### Discussed in https://github.com/samschott/maestral/discussions/938

<div type='discussions-op-text'>

<sup>Originally posted by **schwerd** June 27, 2023</sup>
I've brought this up several times over the past few months. it seems to be intermittent, which doesn't make a whole lot of sense.  I've submitted crashlogs and activity snapshots.  Maestral crashes pretty regularly.  at least several times a day. I've watched and most often it's a complete crash of the UI and the daemon.  and it very often happens when my laptop is closed, therefore asleep, but not shutdown.  I will open the laptop to work, and Maestral is gone.

also, I'm watching it on mulitple OS's.  it is crashing on release version of Ventura as well as dev beta 2 of Sonoma

I'm happy to submit more logs or snapshots to discover possible causes.

I can't believe I'm the only on having these problems.  if they were really sporadic and inconsequential, I'd live with it.  but it's happening several times each day on multiple machines and causing a lot of confusion regarding shared data.  and, it seemed to work flawlessly for a long time.  so I don't know what could have changed.</div>

**Comment by bjoreman** [comment]
Oh I have this too! And I'm getting increasing amounts of confusion with synced files. Not sure if all of it is related to the crashes or if other factors are also at play, but now I am having situations where files which were synced just fine seem to disappear, or become empty on one machine until further syncs are forced. This coming and going feels very worrying.

**Comment by pwood22** [comment]
I'm having the same problem with a macbook pro laptop with M2 pro chip running ventura. Maestral crashes either while the laptop is sleeping, or upon wake.

**Comment by eduardomarossi** [comment]
I also having the same problem.

MacBook Pro 2020 (Intel)
macOS Ventura

**Comment by gabhab** [comment]
Same here (M2 mac mini, Ventura). Does anyone know a way to at least be notified when it happens? I sometimes don't notice for a day (until I realise that it isn't running - it just seems to silently stop without any notification).

**Comment by theandrewwade** [comment]
I thought I commented on this to say "me too" but don't see my comment now. Anyway, on my machine as well. M1 MBP running Ventura.

**Comment by pwood22** [comment]
I don't know whether this is relevant, but the app only appears to crash when in sync mode. If I sleep my MBP after pausing the sync, then everything is fine.

**Comment by schwerd** [comment]
something to look at, but what's the point??  if you turn off sync to keep
it from crashing, it's the same as it crashing as it's not syncing. why
would anyone turn off sync???

**Comment by pwood22** [comment]
I don't turn it off to keep it from crashing, I turn it off because I have limited bandwidth and when I'm working on a large file, the sync process can hog all my available bandwidth each time i save the file. So I pause the sync process and restart once I've finished with the large file... except sometimes I forget 😁
Roll on fibre broadband!

**Comment by schwerd** [comment]
Got it.
Thank you.

**Comment by SalocinHB** [comment]
Same issue here, the Maestral daemon simply stops running without any indication. The logs (`maestral log show`) provide no explanation.

**Comment by jonathanlang** [comment]
Same, I haven't been digging through the crash logs, but I notice regularly that Maestral is no longer running in the background. Hopefully this can get fixed soon.

**Comment by gruber** [comment]
I've been encountering this bug for the last month or so, and published two workarounds for automatically relaunching Maestral while we wait for a proper fix:

https://daringfireball.net/2023/07/nerding_out_with_maestral_launchcontrol_and_keyboard_maestro

**Comment by schwerd** [comment]
same here, this has been an issue for months. I built a Keyboard Maestro
action similar to gruber's.  see if Maestral is running, if not, relaunch
it.  works while we wait for a permanent fix.

**Comment by ulysseskan** [comment]
Is Maestral actually crashing or is it perhaps being forcefully terminated by the CacheDelete framework?  

For reference:
https://bitsplitting.org/2022/06/18/purgeable-mac-apps/
https://developer.apple.com/forums/thread/707643?answerId=717746022#717746022

**Comment by Mr0grog** [comment]
FWIW, I’m seeing slightly different logs than referenced in the above post, but `runningboardd` does make an appearance on my machine (2021 MacBook Pro M1 Pro, MacOS Ventura 13.4.1(c)). I’m seeing logs like this in both cases where I bring my Mac back from sleep and Maestral has died since I saw @ulysseskan’s post:

```
2023-07-20 12:50:47.184137 (pid/60761 [Maestral]) <Notice>: shutting down
2023-07-20 12:50:47.184163 (pid/60761/com.apple.WebKit.WebContent) <Notice>: internal event: PETRIFIED, code = 0
2023-07-20 12:50:47.184175 (pid/60761/com.apple.MTLCompilerService) <Notice>: internal event: PETRIFIED, code = 0
2023-07-20 12:50:47.184182 (pid/60761/com.apple.audio.AUHostingService.x86-64) <Notice>: internal event: PETRIFIED, code = 0
2023-07-20 12:50:47.184187 (pid/60761/com.apple.WebKit.GPU) <Notice>: internal event: PETRIFIED, code = 0
2023-07-20 12:50:47.184194 (pid/60761/com.apple.audio.AUHostingService.arm64e) <Notice>: internal event: PETRIFIED, code = 0
2023-07-20 12:50:47.184199 (pid/60761/com.apple.WebKit.Networking) <Notice>: internal event: PETRIFIED, code = 0
2023-07-20 12:50:47.184205 (pid/60761/com.apple.WebKit.WebContent.Crashy) <Notice>: internal event: PETRIFIED, code = 0
2023-07-20 12:50:47.184211 (pid/60761/com.apple.WebKit.WebContent.Development) <Notice>: internal event: PETRIFIED, code = 0
2023-07-20 12:50:47.184219 (pid/60761/com.apple.audio.Core-Audio-Driver-Service.helper) <Notice>: internal event: PETRIFIED, code = 0
2023-07-20 12:50:47.184224 (pid/60761/com.apple.WebKit.WebContent.CaptivePortal) <Notice>: internal event: PETRIFIED, code = 0
2023-07-20 12:50:47.184229 (pid/60761/com.apple.audio.Core-Audio-Driver-Service) <Notice>: internal event: PETRIFIED, code = 0
2023-07-20 12:50:47.184287 (pid/60761 [Maestral]) <Notice>: cleaning up
2023-07-20 12:50:47.184347 (gui/501/application.com.samschott.maestral.93043937.93044123 [60761]) <Notice>: exited due to exit(0)
2023-07-20 12:50:47.184350 (gui/501/application.com.samschott.maestral.93043937.93044123 [60761]) <Notice>: service state: exited
2023-07-20 12:50:47.184357 (gui/501/application.com.samschott.maestral.93043937.93044123 [60761]) <Notice>: internal event: EXITED, code = 0
2023-07-20 12:50:47.184359 (gui/501/application.com.samschott.maestral.93043937.93044123 [60761]) <Notice>: job state = exited
2023-07-20 12:50:47.184390 (gui/501 [100003]) <Notice>: service inactive: application.com.samschott.maestral.93043937.93044123
2023-07-20 12:50:47.184393 (gui/501/application.com.samschott.maestral.93043937.93044123 [60761]) <Notice>: service state: not running
2023-07-20 12:50:47.184400 (system) <Notice>: removing child: pid/60761
2023-07-20 12:50:47.187736 <Notice>: Flushed 20 logs [limit: 20]
2023-07-20 12:50:47.188073 (gui/501/application.com.samschott.maestral.93043937.93044123) <Notice>: removing job: caller = runningboardd
2023-07-20 12:50:47.188087 (gui/501 [100003]) <Notice>: removing service: application.com.samschott.maestral.93043937.93044123
2023-07-20 12:50:47.188096 (gui/501/application.com.samschott.maestral.93043937.93044123) <Notice>: internal event: PETRIFIED, code = 0
2023-07-20 12:50:47.188099 (gui/501/application.com.samschott.maestral.93043937.93044123) <Notice>: job state = removed
```

That said, after reading these logs, I’m not sure whether this is indicating that RunningBoard is what’s killing it, or if it exited for other reasons that are causing it to quit (`<Notice>: exited due to exit(0)`) and RunningBoard is just noticing that the launchd service is no longer running, and is only cleaning things up. There’s no more detailed RunningBoard code or explanation like in Jalkut’s blog post and the notice about `runningboardd` doesn’t show up until after the logs about Maestral cleanly exiting.

**Comment by gruber** [comment]
That's an interesting guess, but it seems like a different issue. My launchd logs do show when Maestral is exiting though. From `/var/log/com.apple.xpc.launchd/launchd.log`, I see repeated entries like this whenever Maestral exits:

```
2023-07-20 03:21:17.318835 (pid/49799 [Maestral]) <Notice>: shutting down
2023-07-20 03:21:17.318848 (pid/49799 [Maestral]) <Notice>: cleaning up
2023-07-20 03:21:17.318926 (gui/501/application.com.samschott.maestral.271229502.271229688 [49799]) <Notice>: exited due to exit(0)
2023-07-20 03:21:17.318930 (gui/501/application.com.samschott.maestral.271229502.271229688 [49799]) <Notice>: service state: exited
2023-07-20 03:21:17.318936 (gui/501/application.com.samschott.maestral.271229502.271229688 [49799]) <Notice>: internal event: EXITED, code = 0
2023-07-20 03:21:17.318939 (gui/501/application.com.samschott.maestral.271229502.271229688 [49799]) <Notice>: job state = exited
2023-07-20 03:21:17.318981 (gui/501 [100006]) <Notice>: service inactive: application.com.samschott.maestral.271229502.271229688
2023-07-20 03:21:17.318984 (gui/501/application.com.samschott.maestral.271229502.271229688 [49799]) <Notice>: service state: not running
2023-07-20 03:21:17.323345 (gui/501/application.com.samschott.maestral.271229502.271229688) <Notice>: removing job: caller = runningboardd
2023-07-20 03:21:17.323354 (gui/501 [100006]) <Notice>: removing service: application.com.samschott.maestral.271229502.271229688
2023-07-20 03:21:17.323363 (gui/501/application.com.samschott.maestral.271229502.271229688) <Notice>: internal event: PETRIFIED, code = 0
2023-07-20 03:21:17.323365 (gui/501/application.com.samschott.maestral.271229502.271229688) <Notice>: job state = removed
2023-07-20 03:37:00.367309 (gui/501/application.com.samschott.maestral.271229502.271229688) <Notice>: internal event: WILL_SPAWN, code = 0
2023-07-20 03:37:00.367316 (gui/501/application.com.samschott.maestral.271229502.271229688) <Notice>: service state: spawn scheduled
2023-07-20 03:37:00.367318 (gui/501/application.com.samschott.maestral.271229502.271229688) <Notice>: service state: spawning
2023-07-20 03:37:00.367326 <Notice>: Coalition Cache Hit: app<application.com.samschott.maestral.271229502.271229688(501)> [8143]
2023-07-20 03:37:00.367337 (gui/501/application.com.samschott.maestral.271229502.271229688) <Notice>: launching: launch job demand
2023-07-20 03:37:00.367660 (gui/501/application.com.samschott.maestral.271229502.271229688 [50693]) <Notice>: xpcproxy spawned with pid 50693
2023-07-20 03:37:00.367671 (gui/501/application.com.samschott.maestral.271229502.271229688 [50693]) <Notice>: internal event: SPAWNED, code = 0
2023-07-20 03:37:00.367672 (gui/501/application.com.samschott.maestral.271229502.271229688 [50693]) <Notice>: service state: xpcproxy
2023-07-20 03:37:00.367696 (gui/501/application.com.samschott.maestral.271229502.271229688 [50693]) <Notice>: internal event: SOURCE_ATTACH, code = 0
2023-07-20 03:37:00.376894 (gui/501/application.com.samschott.maestral.271229502.271229688 [50693]) <Notice>: service state: running
2023-07-20 03:37:00.376903 (gui/501/application.com.samschott.maestral.271229502.271229688 [50693]) <Notice>: internal event: INIT, code = 0
2023-07-20 03:37:00.376906 (gui/501/application.com.samschott.maestral.271229502.271229688 [50693]) <Notice>: job state = running
2023-07-20 03:37:00.376924 (gui/501/application.com.samschott.maestral.271229502.271229688 [50693]) <Notice>: Successfully spawned Maestral[50693] because launch job demand
2023-07-20 03:37:00.392859 (pid/50693 [Maestral]) <Notice>: uncorking exec source upfront
2023-07-20 03:37:00.392884 (pid/50693 [Maestral]) <Notice>: created
2023-07-20 03:37:01.207273 (gui/501 [100006]) <Warning>: failed lookup: name = com.samschott.maestral-spks, requestor = Maestral[50693], error = 3: No such process
```

This tidbit from those logs makes it look like Maestral isn't crashing, but is exiting on its own: `(gui/501/application.com.samschott.maestral.271229502.271229688 [49799]) <Notice>: exited due to exit(0)`.

**Comment by wo1fjay** [comment]
I'm also having this issue with Maestral on a M2 Max 14" MBP and an M1 Mac Mini, both on Ventura 13.4.1. Can provide logs if necessary (and if someone can explain where to grab them from!)

Also, hi @gruber, love your work 😌✨

**Comment by hempalex** [comment]
As a workaround I've changed in ~/Library/LaunchAgents/com.samschott.maestral.maestral.plist
```diff
- <key>RunAtLoad</key>
+ <key>KeepAlive</key>

```

**Comment by samschott** [comment]
@gruber, that is curious. Any form of segfault should not have an exit code of zero. In Maestral's own logs, do you see any signs of a graceful shutdown coinciding with the systemd logs? It should look like the following:
```
2023-07-24 22:23:15 manager INFO: Shutting down threads...
2023-07-24 22:23:15 sync INFO: Sync aborted
2023-07-24 22:23:15 manager INFO: Paused
```

Apologies for not finding a solution to this, it is very hard to debug without being able to reproduce it myself and without apparent crash logs.

**Comment by schwerd** [comment]
@samschott any chance you could put some debugging dumps in a beta build
and share it with those of us very willing helpers to gather some log
data???  Clearly you have a loyal following that is willing to help
understand what is going on.

**Comment by Mr0grog** [comment]
@samschott This happened again for me overnight, but the logs from `maestral log show` (I assume these are the logs you’re looking for) didn’t seem very revealing. I set the the log level to DEBUG, caught another shut down while the computer was sleeping, and there’s nothing about shutting down.

The last logs are the deletion of some files after a sync (no messages about shutting down, aborting, pausing, etc.). However, it does look like some other weird things are going on:

1. In both this most recent shut down (with DEBUG logs) and the previous (INFO logs), it looks like it has a connection error, aborts then sync, starts a new sync, and then simply exits midway through the sync (the first exit has one additional log line, but otherwise the INFO and higher log lines are the same in both instances). Maybe the sync threads aren’t checking a lock or event and fully shutting down until initiating the next sync, or something along those lines?

2. It appears to be trying to delete some old files that I haven’t touched. Those files show up deleted in Dropbox (!!) at a time briefly before Maestral exited (the Dropbox web UI just says “an hour ago” and I can’t see where/how to get an exact timestamp). Maestral’s logs look like it’s been trying to delete the file for a while (longer than an hour ago), but then logs `sync DEBUG: Equal revs for "<file path>": local item is the same or newer than on Dropbox`. Some but not all of these files have conflicted copies on disk.

<details>

<summary>Fuller logs:</summary>

First exit, launchd logs:

```
2023-07-25 00:22:58.777769 (gui/501/application.com.samschott.maestral.93043937.93044123 [17554]) <Notice>: exited due to exit(0)
2023-07-25 00:22:58.777781 (gui/501/application.com.samschott.maestral.93043937.93044123 [17554]) <Notice>: service state: exited
2023-07-25 00:22:58.777787 (gui/501/application.com.samschott.maestral.93043937.93044123 [17554]) <Notice>: internal event: EXITED, code = 0
2023-07-25 00:22:58.777789 (gui/501/application.com.samschott.maestral.93043937.93044123 [17554]) <Notice>: job state = exited
2023-07-25 00:22:58.777814 (gui/501 [100003]) <Notice>: service inactive: application.com.samschott.maestral.93043937.93044123
2023-07-25 00:22:58.777817 (gui/501/application.com.samschott.maestral.93043937.93044123 [17554]) <Notice>: service state: not running
2023-07-25 00:22:58.777823 (pid/17554 [Maestral]) <Notice>: shutting down
2023-07-25 00:22:58.777826 (pid/17554 [Maestral]) <Notice>: cleaning up
2023-07-25 00:22:58.777832 (system) <Notice>: removing child: pid/17554
2023-07-25 00:22:58.779327 (gui/501/application.com.samschott.maestral.93043937.93044123) <Notice>: removing job: caller = runningboardd
2023-07-25 00:22:58.779341 (gui/501 [100003]) <Notice>: removing service: application.com.samschott.maestral.93043937.93044123
2023-07-25 00:22:58.779350 (gui/501/application.com.samschott.maestral.93043937.93044123) <Notice>: internal event: PETRIFIED, code = 0
2023-07-25 00:22:58.779352 (gui/501/application.com.samschott.maestral.93043937.93044123) <Notice>: job state = removed
```

First exit, Maestral logs (`maestral log show`):

```
2023-07-25 00:09:33 manager INFO: Up to date
2023-07-25 00:22:28 manager INFO: Connection lost
2023-07-25 00:22:28 manager INFO: Shutting down threads...
2023-07-25 00:22:28 sync INFO: Sync aborted
2023-07-25 00:22:28 manager INFO: Paused
2023-07-25 00:22:28 manager INFO: Connecting...
2023-07-25 00:22:30 manager INFO: Connection lost
2023-07-25 00:22:30 manager INFO: Shutting down threads...
2023-07-25 00:22:30 sync INFO: Sync aborted
2023-07-25 00:22:30 manager INFO: Paused
2023-07-25 00:22:30 manager INFO: Connecting...
2023-07-25 00:22:42 sync INFO: Fetching remote changes
2023-07-25 00:22:42 sync INFO: Indexing local changes...
2023-07-25 00:22:46 sync INFO: Uploading deletions...
2023-07-25 00:22:46 sync INFO: Deleting 1/10
2023-07-25 00:22:47 manager INFO: Connection lost
2023-07-25 00:22:47 manager INFO: Shutting down threads...
2023-07-25 00:22:47 sync INFO: Sync aborted
2023-07-25 00:22:47 manager INFO: Paused
2023-07-25 00:22:47 manager INFO: Connecting...
2023-07-25 00:22:52 sync INFO: Fetching remote changes
2023-07-25 00:22:52 sync INFO: Indexing 3...
2023-07-25 00:22:52 sync INFO: Applying deletions...
2023-07-25 00:22:53 sync INFO: Deleting 1/3
2023-07-25 00:22:53 sync INFO: Deleting 2/3
2023-07-25 00:22:53 sync INFO: Deleting 3/3
2023-07-25 00:22:53 sync INFO: Up to date
2023-07-25 00:22:53 sync INFO: Indexing local changes...
2023-07-25 00:22:56 sync INFO: Uploading deletions...
2023-07-25 00:22:57 sync INFO: Deleting 1/7
2023-07-25 00:22:57 sync INFO: Deleting 2/7
2023-07-25 00:22:57 sync INFO: Deleting 3/7
2023-07-25 00:22:57 sync INFO: Deleting 4/7
2023-07-25 00:22:58 sync INFO: Deleting 5/7
2023-07-25 00:22:58 sync INFO: Deleting 6/7
2023-07-25 00:22:58 sync INFO: Deleting 7/7
2023-07-25 00:22:58 sync INFO: Syncing ↑ 1/10
```

---

Second exit, launchd logs:

```
2023-07-25 15:29:48.661295 (gui/501/application.com.samschott.maestral.93043937.93044123 [21484]) <Notice>: exited due to exit(0)
2023-07-25 15:29:48.661311 (gui/501/application.com.samschott.maestral.93043937.93044123 [21484]) <Notice>: service state: exited
2023-07-25 15:29:48.661318 (gui/501/application.com.samschott.maestral.93043937.93044123 [21484]) <Notice>: internal event: EXITED, code = 0
2023-07-25 15:29:48.661321 (gui/501/application.com.samschott.maestral.93043937.93044123 [21484]) <Notice>: job state = exited
2023-07-25 15:29:48.661355 (gui/501/application.com.samschott.maestral.93043937.93044123 [21484]) <Notice>: service state: not running
2023-07-25 15:29:48.661364 (gui/501 [100003]) <Notice>: service inactive: application.com.samschott.maestral.93043937.93044123
2023-07-25 15:29:48.661372 (pid/21484 [Maestral]) <Notice>: shutting down
2023-07-25 15:29:48.661379 (pid/21484/com.apple.WebKit.WebContent) <Notice>: internal event: PETRIFIED, code = 0
2023-07-25 15:29:48.661388 (pid/21484/com.apple.MTLCompilerService) <Notice>: internal event: PETRIFIED, code = 0
2023-07-25 15:29:48.661395 (pid/21484/com.apple.audio.AUHostingService.x86-64) <Notice>: internal event: PETRIFIED, code = 0
2023-07-25 15:29:48.661399 (pid/21484/com.apple.WebKit.GPU) <Notice>: internal event: PETRIFIED, code = 0
2023-07-25 15:29:48.661419 (pid/21484/com.apple.audio.AUHostingService.arm64e) <Notice>: internal event: PETRIFIED, code = 0
2023-07-25 15:29:48.661423 (pid/21484/com.apple.WebKit.Networking) <Notice>: internal event: PETRIFIED, code = 0
2023-07-25 15:29:48.661428 (pid/21484/com.apple.WebKit.WebContent.Crashy) <Notice>: internal event: PETRIFIED, code = 0
2023-07-25 15:29:48.661474 (pid/21484/com.apple.WebKit.WebContent.Development) <Notice>: internal event: PETRIFIED, code = 0
2023-07-25 15:29:48.661480 (pid/21484/com.apple.audio.Core-Audio-Driver-Service.helper) <Notice>: internal event: PETRIFIED, code = 0
2023-07-25 15:29:48.661501 (pid/21484/com.apple.WebKit.WebContent.CaptivePortal) <Notice>: internal event: PETRIFIED, code = 0
2023-07-25 15:29:48.661506 (pid/21484/com.apple.audio.Core-Audio-Driver-Service) <Notice>: internal event: PETRIFIED, code = 0
2023-07-25 15:29:48.661584 (pid/21484 [Maestral]) <Notice>: cleaning up
2023-07-25 15:29:48.661590 (system) <Notice>: removing child: pid/21484
2023-07-25 15:29:48.665334 <Notice>: Flushed 20 logs [limit: 20]
2023-07-25 15:29:48.665514 (gui/501/application.com.samschott.maestral.93043937.93044123) <Notice>: removing job: caller = runningboardd
2023-07-25 15:29:48.665525 (gui/501 [100003]) <Notice>: removing service: application.com.samschott.maestral.93043937.93044123
2023-07-25 15:29:48.665538 (gui/501/application.com.samschott.maestral.93043937.93044123) <Notice>: internal event: PETRIFIED, code = 0
2023-07-25 15:29:48.665541 (gui/501/application.com.samschott.maestral.93043937.93044123) <Notice>: job state = removed
```

Second exit, Maestral logs (`maestral log show`, DEBUG level):

```
2023-07-25 15:29:19 manager INFO: Connecting...
2023-07-25 15:29:29 sync DEBUG: Could not load mignore rules: No such file or directory
2023-07-25 15:29:29 dropbox_client DEBUG: Refreshing access token.
2023-07-25 15:29:30 dropbox_client DEBUG: Request to users/get_space_usage
2023-07-25 15:29:30 manager DEBUG: Checking path root...
2023-07-25 15:29:30 dropbox_client DEBUG: Request to users/get_current_account
2023-07-25 15:29:30 manager DEBUG: Path root is up to date
2023-07-25 15:29:30 sync INFO: Fetching remote changes
2023-07-25 15:29:30 sync DEBUG: Fetching remote changes since cursor: AAHaM5LuRA3QU1TUoFnMwPnzmnUqhf8WIHbESUeHJD3JU0eQaikPgXdNuDoBzBVtLbggvqh965FQQtAp8jKRJc5SkE9iKnNLVixGzZso2
i7t26gRPS7u6CRRFthQcrDPUvsgo_u8TvqU3sTkuEq34nOaCZE4Avs2Y4kcZsmlQzw3lvx-OBZ0ZOhb1SroEQn7wFqVzszg5MAaAiKZU1Hh5UunEPfKwS8rk5lNwsIUs7py7rJdLZUR-gkYeIxpY4_HAI3vMvJq7Jmwn0uwPKdUEhaz
V8KlRbneSzPd-K_H2J-g3dKEwXM7i1LYgkwLRt85Bk6p9mOQeHXG27bt0H9Yz6xzJ6kunOIDO_0P2cWWeYRHaLJvhepq8E4B1cWoXxusBMb5Ye6Duq-P_HYJONwwqZNrJHjOGd327H0Hxz80c-DuA4aUNJn_Wfc7sETUxlIwH0Cyie9
bD7N_kUPrf11WwnIIODu1T-bcLao-LdNpLkOb-5y7WE35Krjy2STaCXVX7RHzO_aKRrq6r-p4SKYM3CfuXF3LgVjNi4OkbeH2A3kY9VB8Bply1wWpXTePCKbgyPqCORc4uYiDUP5qUPelNBup-Xk3kaZ1PtaaNJhTG1-jpMCi0yfUFQ
sAr_q4sFpamTxmwdEbt__CmAiOCUU_iplp5v69SNC5WV4N2D24OlvLDQehNPBZ9HhYJmrwZspMzzxDoXB-VbwgOPOKz5H_1KKfbp5kRk7aln8VW6SsJC02JoNnNeRRcGd6e0Hy_hnTV3cec0rn3TfB7hRBWntecdGoQWzbiRhpQ1vsR
bPQVPmsyStrS9Cukzh16PQynsU67OStnCcPH53DsRIUZjh5IEn-8FSS9WRdSFlgcM8tykJNiyMDrz9fg2r9jQlcs3DNo-fkIq1GH2O0O7gPVpHkHNGDtfHnPSlus0dn7QZ4EHnYv-Ha4-w5nZxFdz83TptQhVj7UoQAH_nW-aDfDfvG
y2BAMe47mkpP-SNtHWW8eVB-FYq0ASHb7WScWyxlZl4vEFCe2G8hqrktwetG57rFfcg8OYZApx5Z86HoyYtj9-qqb3pZgRljGApZ3Ey1ezBbyBa1p7s-OrF8WgfY2ofClpztEdbh1NKcML_HBvfmW9wKJdZWJSOibzzVsd_3G2Lh4BT
IjLf6jmfpXfHEUicPnsW5yCmYjGsvMPD-3ct3UYxSDn8jm3Lo6jZKDatOYWpPKeTEDo4-JlfCxlRCUwPnIgJAWhCZrRcqm31Z6QZiHGYVIAu-4QLh2gn6dM2vFZO-yu8bVDCw-7FFpF-CzB629mznqkRNyng1_YTwMojqxOdiGlzNwX
3rZntjjboXuv_M8D4
2023-07-25 15:29:30 dropbox_client DEBUG: Refreshing access token.
2023-07-25 15:29:30 dropbox_client DEBUG: Request to files/list_folder/continue
2023-07-25 15:29:30 sync DEBUG: Remote changes:
[]
2023-07-25 15:29:30 sync DEBUG: Converted remote changes to SyncEvents
2023-07-25 15:29:30 sync DEBUG: Remote cursor saved: AAG_YjNUGkfCWcjcxCpg7Ly0ZwlFugV--ynHXRvx1-XH_yYripgMvYHkzPwpy7T8W8RXmHS8K_QO-z9sRbJYa0yt7ty1uQT-_Ak-dywCYcwnqtOhdeoeLXcuNs
k2fIZpih0vXwO4_bn2HILbuBMDXp900TBOltVwt0SDoujnnldxBL77x6fFHxfNM759aOSulUfPMCeLYj3nDFaxsVGSu4WutuMiaAPfMVmEM-erjuSsbfR2ANDzLCYk6B23S0WXs6dPtxnHg7dGhPbW5yHbyZabf4I5TYy8E2q8X5qOZ
IAP36kClSLuoLicheZYV6l1MORiNDAlUkrp3HMSNGufICQFwpXWPNYn4HYdSF1mRlXSUmsXz1nA_4uImvNtJ693aEcSGG5vPZJlUBCt4G4PcW9AlvHQhq_akRvGfvOYFZx6FJJQ-1slYR_bQarpVQ-3Q-WtFoS3XBsttWAakI-b_s9W
V_x0HxdPi8h0d91O0feu5Jn7sS_o9yPPJ9-pUL53xz35p1ByDY-FNtRcTXDm19iHd6E9xnUF-m6rbkPOeYYn12Z2lObY8yCfZWrzGQWvctXwJtkISvEqDMqcui-dU9jY7WNTFtZ1wPkCJD9NZLK9GIlw7kmKDpHoj9Wt90Zumh_ftOf
VyaOgO52klzTII5cCcLOm9t6UGR_71dITjYdNDfdcf4luRuvghp7g9f3xy5uJiZ5wMv7b_fQc_v7MNa3ZgkjaCkOSBkxpLTwoD3TJyv1qog9fkm5bqiGsFk81JNRoO8VVrV8mFBLoTrLie9pXqNq5fyOsIY9Uek1--WUluZGP_0abCT
iduoR3rythl60zVcHwz2QS5Ig6sLFRo1a5cUV7lds2mjDv96uLximzkyNQ2DG7tV-yfV5o4nA3AQI4K2hIujTUw5GnkWnEVrBS0C41o2iL13hMp6YoQDImPvitWxHhNA6obyK0h0m75XwyqjVqqOtQt-2FvCrLQl0X8dBYJf4bgH7S8
JInusJWY_Qk9CyM-DmzIQi0kE_OjnA8SgM1p8e5243W6ZnfzBvCTPfzxWl2m5eABszMBwuDvQUUhf20U1Z-UUxT-YvTGm50DQASuoA0CIAoHIoCE-dS1U49za3bAc10q1iDuJrxuYOJAh9iwLk9nkPkWyWi9CIgHA00MYEoXfXPXwAk
e74828ex0OqYFnubt2hyEHsaXOm5YWQMwMWo77t7-XW4YaDM48ABQiowXQz0Ho0S0zczUm7Y1kBB-v3tnv1XEq7k-oZKahmnkHbTtLTXk2uFg5O42CO5-nBrNPBCEui1PQU_69y3kh7sv_FJmNaxiPDA14ut9Uwcu35X-rR2mat0IGw
2023-07-25 15:29:30 sync DEBUG: Pruning sync errors
2023-07-25 15:29:30 sync INFO: Indexing local changes...
2023-07-25 15:29:34 sync DEBUG: Local indexing completed in 3.3386 sec
2023-07-25 15:29:34 sync DEBUG: Retrieved local changes:
[<FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Sopa de Albóndigas (Mexican Meatball Soup).pdf', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Diana Dávila’s Chiles Rellenos.pdf', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Corn, Bacon and Cheddar Pie With Pickled Jalapeños.pdf', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Quick Ragù With Ricotta and Lemon.html', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Gruyère Puff.html', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Quick Ragù With Ricotta and Lemon.pdf', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Diana Dávila’s Chiles Rellenos.webarchive', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Pastelón.pdf', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Café China’s Dan Dan Noodles.pdf', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Official/Receipts 2013/2013-06-28 The Private Eye - Marcos Martín.pdf', is_directory=False>,
 <FileDeletedEvent: event_type=deleted, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Corn, Bacon and Cheddar Pie With Pickled Jalapeños.pdf', is_directory=False>,
 <FileDeletedEvent: event_type=deleted, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Gruyère Puff.html', is_directory=False>,
 <FileDeletedEvent: event_type=deleted, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Diana Dávila’s Chiles Rellenos.pdf', is_directory=False>,
 <FileDeletedEvent: event_type=deleted, src_path='/Users/rbrackett/Dropbox/Official/Receipts 2013/2013-06-28 The Private Eye - Marcos Martín.pdf', is_directory=False>,
 <FileDeletedEvent: event_type=deleted, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Café China’s Dan Dan Noodles.pdf', is_directory=False>,
 <FileDeletedEvent: event_type=deleted, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Sopa de Albóndigas (Mexican Meatball Soup).pdf', is_directory=False>,
 <FileDeletedEvent: event_type=deleted, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Quick Ragù With Ricotta and Lemon.pdf', is_directory=False>,
 <FileDeletedEvent: event_type=deleted, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Pastelón.pdf', is_directory=False>,
 <FileDeletedEvent: event_type=deleted, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Diana Dávila’s Chiles Rellenos.webarchive', is_directory=False>,
 <FileDeletedEvent: event_type=deleted, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Quick Ragù With Ricotta and Lemon.html', is_directory=False>]
2023-07-25 15:29:34 sync DEBUG: Filtered deleted events:
[<SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Removed, item_type=ItemType.File, dbx_path=/Official/Receipts 2013/2013-06-28 The Private Eye - Marcos Martín.pd
f)>,
 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Removed, item_type=ItemType.File, dbx_path=/Docs/Recipes/Corn, Bacon and Cheddar Pie With Pickled Jalapeños.pdf)
>,
 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Removed, item_type=ItemType.File, dbx_path=/Docs/Recipes/Gruyère Puff.html)>,
 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Removed, item_type=ItemType.File, dbx_path=/Docs/Recipes/Diana Dávila’s Chiles Rellenos.pdf)>,
 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Removed, item_type=ItemType.File, dbx_path=/Docs/Recipes/Pastelón.pdf)>,
 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Removed, item_type=ItemType.File, dbx_path=/Docs/Recipes/Quick Ragù With Ricotta and Lemon.pdf)>,
 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Removed, item_type=ItemType.File, dbx_path=/Docs/Recipes/Diana Dávila’s Chiles Rellenos.webarchive)>,
 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Removed, item_type=ItemType.File, dbx_path=/Docs/Recipes/Quick Ragù With Ricotta and Lemon.html)>,
 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Removed, item_type=ItemType.File, dbx_path=/Docs/Recipes/Café China’s Dan Dan Noodles.pdf)>,
 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Removed, item_type=ItemType.File, dbx_path=/Docs/Recipes/Sopa de Albóndigas (Mexican Meatball Soup).pdf)>]
2023-07-25 15:29:34 sync DEBUG: Filtered dir moved events:
[]
2023-07-25 15:29:34 sync DEBUG: Filtered other events:
defaultdict(<class 'list'>,
            {3: [<SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Modified, item_type=ItemType.File, dbx_path=/Docs/Recipes/Diana Dávila’s Chiles Rellenos.pdf)>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Modified, item_type=ItemType.File, dbx_path=/Docs/Recipes/Quick Ragù With Ricotta and Lemon.html
)>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Modified, item_type=ItemType.File, dbx_path=/Docs/Recipes/Sopa de Albóndigas (Mexican Meatball S
oup).pdf)>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Modified, item_type=ItemType.File, dbx_path=/Docs/Recipes/Corn, Bacon and Cheddar Pie With Pickl
ed Jalapeños.pdf)>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Modified, item_type=ItemType.File, dbx_path=/Docs/Recipes/Café China’s Dan Dan Noodles.pdf)>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Modified, item_type=ItemType.File, dbx_path=/Docs/Recipes/Gruyère Puff.html)>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Modified, item_type=ItemType.File, dbx_path=/Docs/Recipes/Quick Ragù With Ricotta and Lemon.pdf)
>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Modified, item_type=ItemType.File, dbx_path=/Docs/Recipes/Pastelón.pdf)>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Modified, item_type=ItemType.File, dbx_path=/Official/Receipts 2013/2013-06-28 The Private Eye -
 Marcos Martín.pdf)>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Modified, item_type=ItemType.File, dbx_path=/Docs/Recipes/Diana Dávila’s Chiles Rellenos.webarch
ive)>]})
2023-07-25 15:29:34 sync INFO: Uploading deletions...
2023-07-25 15:29:34 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:34 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:34 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:34 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:34 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:34 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:34 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:34 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:34 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:34 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:34 sync INFO: Deleting 1/10
2023-07-25 15:29:34 dropbox_client DEBUG: Request to files/delete_v2
2023-07-25 15:29:34 dropbox_client DEBUG: Request to files/delete_v2
2023-07-25 15:29:34 dropbox_client DEBUG: Request to files/delete_v2
2023-07-25 15:29:35 manager DEBUG: Connection error
Traceback (most recent call last):
  File "app_packages/urllib3/connectionpool.py", line 790, in urlopen
  File "app_packages/urllib3/connectionpool.py", line 536, in _make_request
  File "app_packages/urllib3/connection.py", line 454, in getresponse
  File "support/python-stdlib/http/client.py", line 1374, in getresponse
  File "support/python-stdlib/http/client.py", line 318, in begin
  File "support/python-stdlib/http/client.py", line 287, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_packages/requests/adapters.py", line 486, in send
  File "app_packages/urllib3/connectionpool.py", line 844, in urlopen
  File "app_packages/urllib3/util/retry.py", line 470, in increment
  File "app_packages/urllib3/util/util.py", line 38, in reraise
  File "app_packages/urllib3/connectionpool.py", line 790, in urlopen
  File "app_packages/urllib3/connectionpool.py", line 536, in _make_request
  File "app_packages/urllib3/connection.py", line 454, in getresponse
  File "support/python-stdlib/http/client.py", line 1374, in getresponse
  File "support/python-stdlib/http/client.py", line 318, in begin
  File "support/python-stdlib/http/client.py", line 287, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_packages/maestral/errorhandling.py", line 90, in convert_api_errors
  File "app_packages/maestral/client.py", line 706, in get_metadata
  File "app_packages/dropbox/base.py", line 1671, in files_get_metadata
  File "app_packages/dropbox/dropbox_client.py", line 326, in request
  File "app_packages/dropbox/dropbox_client.py", line 476, in request_json_string_with_retry
  File "app_packages/maestral/client.py", line 165, in request_json_string
  File "app_packages/dropbox/dropbox_client.py", line 589, in request_json_string
  File "app_packages/requests/sessions.py", line 637, in post
  File "app_packages/requests/sessions.py", line 589, in request
  File "app_packages/requests/sessions.py", line 703, in send
  File "app_packages/requests/adapters.py", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_packages/maestral/manager.py", line 771, in _handle_sync_thread_errors
  File "app_packages/maestral/manager.py", line 757, in startup_worker
  File "app_packages/maestral/sync.py", line 1710, in upload_local_changes_while_inactive
  File "app_packages/maestral/sync.py", line 1955, in apply_local_changes
  File "app_packages/maestral/sync.py", line 3848, in do_parallel
  File "support/python-stdlib/concurrent/futures/_base.py", line 449, in result
  File "support/python-stdlib/concurrent/futures/_base.py", line 401, in __get_result
  File "support/python-stdlib/concurrent/futures/thread.py", line 58, in run
  File "app_packages/maestral/sync.py", line 2317, in _create_remote_entry
  File "app_packages/maestral/sync.py", line 2626, in _on_local_deleted
  File "app_packages/maestral/client.py", line 705, in get_metadata
  File "support/python-stdlib/contextlib.py", line 155, in __exit__
  File "app_packages/maestral/errorhandling.py", line 95, in convert_api_errors
maestral.exceptions.DropboxConnectionError: Cannot connect to Dropbox. Please check you internet connection and try again later.
2023-07-25 15:29:35 manager INFO: Connection lost
2023-07-25 15:29:35 manager INFO: Shutting down threads...
2023-07-25 15:29:35 sync INFO: Sync aborted
2023-07-25 15:29:35 manager INFO: Paused
2023-07-25 15:29:35 manager INFO: Connecting...
2023-07-25 15:29:40 sync DEBUG: Could not load mignore rules: No such file or directory
2023-07-25 15:29:40 dropbox_client DEBUG: Request to users/get_space_usage
2023-07-25 15:29:40 manager DEBUG: Checking path root...
2023-07-25 15:29:40 dropbox_client DEBUG: Request to users/get_current_account
2023-07-25 15:29:40 manager DEBUG: Path root is up to date
2023-07-25 15:29:40 sync INFO: Fetching remote changes
2023-07-25 15:29:40 sync DEBUG: Fetching remote changes since cursor: AAG_YjNUGkfCWcjcxCpg7Ly0ZwlFugV--ynHXRvx1-XH_yYripgMvYHkzPwpy7T8W8RXmHS8K_QO-z9sRbJYa0yt7ty1uQT-_Ak-dywCY
cwnqtOhdeoeLXcuNsk2fIZpih0vXwO4_bn2HILbuBMDXp900TBOltVwt0SDoujnnldxBL77x6fFHxfNM759aOSulUfPMCeLYj3nDFaxsVGSu4WutuMiaAPfMVmEM-erjuSsbfR2ANDzLCYk6B23S0WXs6dPtxnHg7dGhPbW5yHbyZab
f4I5TYy8E2q8X5qOZIAP36kClSLuoLicheZYV6l1MORiNDAlUkrp3HMSNGufICQFwpXWPNYn4HYdSF1mRlXSUmsXz1nA_4uImvNtJ693aEcSGG5vPZJlUBCt4G4PcW9AlvHQhq_akRvGfvOYFZx6FJJQ-1slYR_bQarpVQ-3Q-WtFoS
3XBsttWAakI-b_s9WV_x0HxdPi8h0d91O0feu5Jn7sS_o9yPPJ9-pUL53xz35p1ByDY-FNtRcTXDm19iHd6E9xnUF-m6rbkPOeYYn12Z2lObY8yCfZWrzGQWvctXwJtkISvEqDMqcui-dU9jY7WNTFtZ1wPkCJD9NZLK9GIlw7kmKDp
Hoj9Wt90Zumh_ftOfVyaOgO52klzTII5cCcLOm9t6UGR_71dITjYdNDfdcf4luRuvghp7g9f3xy5uJiZ5wMv7b_fQc_v7MNa3ZgkjaCkOSBkxpLTwoD3TJyv1qog9fkm5bqiGsFk81JNRoO8VVrV8mFBLoTrLie9pXqNq5fyOsIY9Ue
k1--WUluZGP_0abCTiduoR3rythl60zVcHwz2QS5Ig6sLFRo1a5cUV7lds2mjDv96uLximzkyNQ2DG7tV-yfV5o4nA3AQI4K2hIujTUw5GnkWnEVrBS0C41o2iL13hMp6YoQDImPvitWxHhNA6obyK0h0m75XwyqjVqqOtQt-2FvCrL
Ql0X8dBYJf4bgH7S8JInusJWY_Qk9CyM-DmzIQi0kE_OjnA8SgM1p8e5243W6ZnfzBvCTPfzxWl2m5eABszMBwuDvQUUhf20U1Z-UUxT-YvTGm50DQASuoA0CIAoHIoCE-dS1U49za3bAc10q1iDuJrxuYOJAh9iwLk9nkPkWyWi9CI
gHA00MYEoXfXPXwAke74828ex0OqYFnubt2hyEHsaXOm5YWQMwMWo77t7-XW4YaDM48ABQiowXQz0Ho0S0zczUm7Y1kBB-v3tnv1XEq7k-oZKahmnkHbTtLTXk2uFg5O42CO5-nBrNPBCEui1PQU_69y3kh7sv_FJmNaxiPDA14ut9U
wcu35X-rR2mat0IGw
2023-07-25 15:29:40 dropbox_client DEBUG: Request to files/list_folder/continue
2023-07-25 15:29:41 sync DEBUG: Remote changes:
[DeletedMetadata(name='Quick Ragù With Ricotta and Lemon.pdf',
                 path_lower='/docs/recipes/quick ragù with ricotta and '
                            'lemon.pdf',
                 path_display='/Docs/Recipes/Quick Ragù With Ricotta and '
                              'Lemon.pdf'),
 DeletedMetadata(name='Corn, Bacon and Cheddar Pie With Pickled Jalapeños.pdf',
                 path_lower='/docs/recipes/corn, bacon and cheddar pie with '
                            'pickled jalapeños.pdf',
                 path_display='/Docs/Recipes/Corn, Bacon and Cheddar Pie With '
                              'Pickled Jalapeños.pdf'),
 DeletedMetadata(name='2013-06-28 The Private Eye - Marcos Martín.pdf',
                 path_lower='/official/receipts 2013/2013-06-28 the private '
                            'eye - marcos martín.pdf',
                 path_display='/Official/Receipts 2013/2013-06-28 The Private '
                              'Eye - Marcos Martín.pdf')]
2023-07-25 15:29:41 sync DEBUG: Converted remote changes to SyncEvents
2023-07-25 15:29:41 sync INFO: Indexing 3...
2023-07-25 15:29:41 sync INFO: Applying deletions...
2023-07-25 15:29:42 sync DEBUG: Equal revs for "/Docs/Recipes/Quick Ragù With Ricotta and Lemon.pdf": local item is the same or newer than on Dropbox
2023-07-25 15:29:42 sync DEBUG: Equal revs for "/Docs/Recipes/Corn, Bacon and Cheddar Pie With Pickled Jalapeños.pdf": local item is the same or newer than on Dropbox
2023-07-25 15:29:42 sync DEBUG: Equal revs for "/Official/Receipts 2013/2013-06-28 The Private Eye - Marcos Martín.pdf": local item is the same or newer than on Dropbox
2023-07-25 15:29:42 sync INFO: Deleting 1/3
2023-07-25 15:29:42 sync INFO: Deleting 2/3
2023-07-25 15:29:42 sync INFO: Deleting 3/3
2023-07-25 15:29:42 sync DEBUG: Remote cursor saved: AAF70stUp5-jFLDNaEQkBHdp5g8kgb0F9tURkFxFSXUKt-7_Q-fNqZX6l95oFbp5JhzP5k73a_gy_tl6uZddDhZQ3zhQOP35-SgHRZfHVc71gn-OO1wA3jXdMD
Ayzu9nZvD_2ocvK5HmIZXHC0X2s4btetB1mjW1kKxkpH8DT-NOg6hmSSVx9SGk2lVsRdo9NhmQFFFPPRc5niY-JFzL_e54B89l_ORWxbG01z-4GrqaPYt07IgtYn20Rp3QWJlG5sSBND8K1HL2uMNxj8O3Dr16adERsTQ-GsUGG9245
Cj_UBz1ijIQ7phMVXD3-kJsEBBxRsdBdmHyq2rBPLb9OuWnwriroU47vP5MZlOS_BElhoikfUejV-8p0yC4j-lM5cKycFqBpwaVunmXDmDnSk17A96XnMejIYJkDSG7DkULsBnyo5Q23ALP3E0BhuVge9EQZHdu0TsG1YPJGnZ2UWxi
GiREVIc9HGddQaxohTTNv-mfZyUh11idkVAggcwOENarN6bkE_KKR-qL63fVcVbFhXkGBg6L8rkeV7Pkz30h_Z_nRacIlMHm9NL_3sV2UNPDlEJaZWgLehp4Q6siarcudjdvzPcjR2DawdYy8kHCI6jcbEImOSVaXy6hgHB2qcHXYEr
o7IeIuQNzQQauEQkhhPPgQKQc-TM8RNWlBOJcD3duHyl9WANBvX4DpO1L94ZQouQYMc_HlfJoca-i1LGeJvbkgirPeQbrJ06KQoDUWFYd3IkEPXkkMn2mHFoFH7aaVD9F2o039RjEGWEXr5LlbnOKhFMef1lqX-FA-FNhq_C6HU7N1T
q4l6qW8zXvfrzyV4I8jHntvcZPRPn0tnlbzsvw338sOOK3UHmBfsY52K3woOeTYhJvc1g6ZZkULgFKO_psIZyBpFbIIHckcd1v0grd_CUzVMPlHFFF-HrBWdPn631_nA6sClmjc16M5H7_ifuK6l2NkZYwaF0lr64bBqYdgt58ygI82
pMMx83EJGLPjGewrRs_HXLMzh3XIFjAY72phwzPNsPg7jyX74DG8p0WlNpGhCxHMCFxwnNzzeeUJ18h9gwFPHg1CQTIMQ9Ahd8p7WvbfTiSMZgkTWTSboGvdnOEeu7L9LnH6rD_1ZQXgiJRa3bW8jCjvyR1aNPNC9qWv3G7i_lCk4L5
v3bzVlesJdOZqoCDo-BaXueapc1F25qjAMJQRhCwpV5J1SA0t4azOgE7-gVrCRdqQeglZdw34fR-Z-JQPEHCa-7yJFyMeNRcaV68W_PwPcupVg1dtiw2mhh8km1pqrnRqlVTM-yJXNLK-RnJUfC4MpcdkVXpHUbCpf7VBT9QngB8ppk
2023-07-25 15:29:42 sync INFO: Up to date
2023-07-25 15:29:42 sync DEBUG: Pruning sync errors
2023-07-25 15:29:42 sync INFO: Indexing local changes...
2023-07-25 15:29:46 sync DEBUG: Local indexing completed in 4.1555 sec
2023-07-25 15:29:46 sync DEBUG: Retrieved local changes:
[<FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Sopa de Albóndigas (Mexican Meatball Soup).pdf', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Diana Dávila’s Chiles Rellenos.pdf', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Corn, Bacon and Cheddar Pie With Pickled Jalapeños.pdf', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Quick Ragù With Ricotta and Lemon.html', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Gruyère Puff.html', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Quick Ragù With Ricotta and Lemon.pdf', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Diana Dávila’s Chiles Rellenos.webarchive', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Pastelón.pdf', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Café China’s Dan Dan Noodles.pdf', is_directory=False>,
 <FileCreatedEvent: event_type=created, src_path='/Users/rbrackett/Dropbox/Official/Receipts 2013/2013-06-28 The Private Eye - Marcos Martín.pdf', is_directory=False>,
 <FileDeletedEvent: event_type=deleted, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Gruyère Puff.html', is_directory=False>,
 <FileDeletedEvent: event_type=deleted, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Diana Dávila’s Chiles Rellenos.pdf', is_directory=False>,
 <FileDeletedEvent: event_type=deleted, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Café China’s Dan Dan Noodles.pdf', is_directory=False>,
 <FileDeletedEvent: event_type=deleted, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Sopa de Albóndigas (Mexican Meatball Soup).pdf', is_directory=False>,
 <FileDeletedEvent: event_type=deleted, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Pastelón.pdf', is_directory=False>,
 <FileDeletedEvent: event_type=deleted, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Diana Dávila’s Chiles Rellenos.webarchive', is_directory=False>,
 <FileDeletedEvent: event_type=deleted, src_path='/Users/rbrackett/Dropbox/Docs/Recipes/Quick Ragù With Ricotta and Lemon.html', is_directory=False>]
2023-07-25 15:29:46 sync DEBUG: Filtered deleted events:
[<SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Removed, item_type=ItemType.File, dbx_path=/Docs/Recipes/Gruyère Puff.html)>,
 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Removed, item_type=ItemType.File, dbx_path=/Docs/Recipes/Diana Dávila’s Chiles Rellenos.pdf)>,
 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Removed, item_type=ItemType.File, dbx_path=/Docs/Recipes/Café China’s Dan Dan Noodles.pdf)>,
 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Removed, item_type=ItemType.File, dbx_path=/Docs/Recipes/Sopa de Albóndigas (Mexican Meatball Soup).pdf)>,
 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Removed, item_type=ItemType.File, dbx_path=/Docs/Recipes/Pastelón.pdf)>,
 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Removed, item_type=ItemType.File, dbx_path=/Docs/Recipes/Diana Dávila’s Chiles Rellenos.webarchive)>,
 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Removed, item_type=ItemType.File, dbx_path=/Docs/Recipes/Quick Ragù With Ricotta and Lemon.html)>]
2023-07-25 15:29:46 sync DEBUG: Filtered dir moved events:
[]
2023-07-25 15:29:46 sync DEBUG: Filtered other events:
defaultdict(<class 'list'>,
            {3: [<SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Modified, item_type=ItemType.File, dbx_path=/Docs/Recipes/Diana Dávila’s Chiles Rellenos.pdf)>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Modified, item_type=ItemType.File, dbx_path=/Docs/Recipes/Sopa de Albóndigas (Mexican Meatball S
oup).pdf)>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Added, item_type=ItemType.File, dbx_path=/Docs/Recipes/Quick Ragù With Ricotta and Lemon.pdf)>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Modified, item_type=ItemType.File, dbx_path=/Docs/Recipes/Diana Dávila’s Chiles Rellenos.webarch
ive)>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Modified, item_type=ItemType.File, dbx_path=/Docs/Recipes/Café China’s Dan Dan Noodles.pdf)>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Modified, item_type=ItemType.File, dbx_path=/Docs/Recipes/Gruyère Puff.html)>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Modified, item_type=ItemType.File, dbx_path=/Docs/Recipes/Pastelón.pdf)>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Modified, item_type=ItemType.File, dbx_path=/Docs/Recipes/Quick Ragù With Ricotta and Lemon.html
)>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Added, item_type=ItemType.File, dbx_path=/Official/Receipts 2013/2013-06-28 The Private Eye - Ma
rcos Martín.pdf)>,
                 <SyncEvent(direction=SyncDirection.Up, change_type=ChangeType.Added, item_type=ItemType.File, dbx_path=/Docs/Recipes/Corn, Bacon and Cheddar Pie With Pickled
Jalapeños.pdf)>]})
2023-07-25 15:29:46 sync INFO: Uploading deletions...
2023-07-25 15:29:46 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:46 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:46 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:46 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:46 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:46 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:46 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:46 dropbox_client DEBUG: Request to files/delete_v2
2023-07-25 15:29:46 sync INFO: Deleting 1/7
2023-07-25 15:29:46 dropbox_client DEBUG: Request to files/delete_v2
2023-07-25 15:29:46 dropbox_client DEBUG: Request to files/delete_v2
2023-07-25 15:29:47 dropbox_client DEBUG: Request to files/delete_v2
2023-07-25 15:29:47 dropbox_client DEBUG: Request to files/delete_v2
2023-07-25 15:29:47 dropbox_client DEBUG: Request to files/delete_v2
2023-07-25 15:29:47 dropbox_client DEBUG: Request to files/delete_v2
2023-07-25 15:29:47 sync INFO: Deleting 2/7
2023-07-25 15:29:47 sync INFO: Deleting 3/7
2023-07-25 15:29:47 sync INFO: Deleting 4/7
2023-07-25 15:29:48 sync INFO: Deleting 5/7
2023-07-25 15:29:48 sync INFO: Deleting 6/7
2023-07-25 15:29:48 sync INFO: Deleting 7/7
2023-07-25 15:29:48 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:48 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:48 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:48 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:48 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:48 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:48 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:48 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:48 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:48 dropbox_client DEBUG: Request to files/get_metadata
2023-07-25 15:29:48 dropbox_client DEBUG: Request to files/upload
2023-07-25 15:29:48 dropbox_client DEBUG: Request to files/upload
2023-07-25 15:29:48 dropbox_client DEBUG: Request to files/upload
2023-07-25 15:29:48 dropbox_client DEBUG: Request to files/upload
2023-07-25 15:29:48 dropbox_client DEBUG: Request to files/upload
2023-07-25 15:29:48 dropbox_client DEBUG: Request to files/upload
```

</details>

**Comment by Mr0grog** [comment]
Actually, the second item (file deletion issues) sounds a lot like #936, which I see was fixed in 1.8.0 (these logs are from 1.7.3).

**Comment by Mr0grog** [comment]
Same here so far: no crash overnight after upgrading to 1.8.0 yesterday.

**Comment by samschott** [comment]
Well, I did not change anything that should affect crashes in Maestral itself, but I did update all 3rd party dependencies that are part of the macOS app bundle. Among those is `rubicon-objc` which Maestral uses as a bridge between Python and Objective-C. Any segfaults are likely to happen at this layer, so fingers crossed.

**Comment by gruber** [comment]
> @gruber, that is curious. Any form of segfault should not have an exit code of zero. In Maestral's own logs, do you see any signs of a graceful shutdown coinciding with the systemd logs? It should look like the following:
> 
> ```
> 2023-07-24 22:23:15 manager INFO: Shutting down threads...
> 2023-07-24 22:23:15 sync INFO: Sync aborted
> 2023-07-24 22:23:15 manager INFO: Paused
> ```

I don't see lines like those in *~/Library/Logs/maestral/maestral.log*, but I *do* see a unique pair of lines in that log that correspond exactly to when my AppleScript relaunches Maestral:

```
2023-07-21 07:01:29 daemon INFO: Starting daemon
2023-07-21 07:01:30 manager INFO: Connected
```

Here's what I see *before* those lines in the log. There are some "connection lost" and "shutting down" stuff in there:

```
2023-07-21 06:30:31 sync INFO: Up to date
2023-07-21 06:30:31 manager INFO: Up to date
2023-07-21 06:46:11 manager INFO: Connection lost
2023-07-21 06:46:11 manager INFO: Shutting down threads...
2023-07-21 06:46:11 sync INFO: Sync aborted
2023-07-21 06:46:11 manager INFO: Paused
2023-07-21 06:46:11 manager INFO: Connecting...
2023-07-21 06:46:16 manager INFO: Connection lost
2023-07-21 06:46:16 manager INFO: Shutting down threads...
2023-07-21 06:46:16 sync INFO: Sync aborted
2023-07-21 06:46:16 manager INFO: Paused
2023-07-21 06:46:16 manager INFO: Connecting...
2023-07-21 06:46:28 sync INFO: Fetching remote changes
2023-07-21 06:46:28 sync INFO: Indexing local changes...
2023-07-21 06:46:37 sync INFO: Uploading deletions...
2023-07-21 06:46:38 sync INFO: Deleting 1/5
2023-07-21 06:46:38 manager INFO: Connection lost
2023-07-21 06:46:38 manager INFO: Shutting down threads...
2023-07-21 06:46:38 sync INFO: Sync aborted
2023-07-21 06:46:38 manager INFO: Paused
2023-07-21 06:46:38 manager INFO: Connecting...
2023-07-21 06:46:48 sync INFO: Fetching remote changes
2023-07-21 06:46:48 sync INFO: Indexing 3...
2023-07-21 06:46:48 sync INFO: Applying deletions...
2023-07-21 06:46:48 sync INFO: Deleting 1/1
2023-07-21 06:46:49 sync INFO: Deleting 1/2
2023-07-21 06:46:49 sync INFO: Deleting 2/2
2023-07-21 06:46:49 sync INFO: Up to date
2023-07-21 06:46:49 sync INFO: Indexing local changes...
2023-07-21 06:46:58 sync INFO: Uploading deletions...
2023-07-21 06:46:59 sync INFO: Deleting 1/2
2023-07-21 06:46:59 sync INFO: Deleting 2/2
2023-07-21 07:01:29 daemon INFO: Starting daemon
2023-07-21 07:01:30 manager INFO: Connected
```

**Comment by gruber** [comment]
I only upgraded from 1.7.3 to 1.8.0 just now (Wednesday, 26 July). But I noticed that Maestral stopped quitting in the background on Friday. My auto-relaunching AppleScript hadn't posted a notification since Friday morning.

Here's a weird possible correlation. I'm a terrible web browser tab hoarder. Right now I have 31 Safari windows open containing 429 tabs. Ordinarily this is just fine -- I maxed out my MBP with 64 GB of RAM mainly to support my browser tab habit. But every week or two I find Safari gets bogged down and I quit and relaunch it. I have Safari set to reopen all previous open tabs upon relaunch, but starting over fresh, even with hundreds of tabs, usually clears up a lot of memory.

I'm pretty sure the problem we're discussing in this thread does not involve Maestral *crashing*. Somehow it's exiting or being exited. Is this possibly related? I forget the name of it, and web searches aren't helping me, but I seem to recall that MacOS recently added some sort of feature where processes without any visible UI can get reaped by the system when it wants to reclaim resources like memory. I'm wondering if this problem only happens when available free memory is "low".

**Comment by theandrewwade** [comment]
Interesting idea, but I doubt that's the issue ("It's not your fault"). My 14" MBP had the issue and I'm not a Windows of Siracusa County guy. RAM tends to sit around 50% most of the time. It is certainly not under any heavy loads. Don't tell Johny but I mainly got it for the HDMI port.

That said, I haven't had it quit on me this week. Maybe last Friday was the magic day but I haven't been running logs.

Thanks Sam for the update!

**Comment by jonathanlang** [comment]
Same here, very stable since updating to 1.8.0. Thanks!

**Comment by ageva8** [comment]
Is people's impression that this bug has been resolved w/1.8.0? Not my experience. Happy to help debug if I can somehow.

**Comment by jonathanlang** [comment]
> Is people's impression that this bug has been resolved w/1.8.0? Not my experience. Sonoma 14.1. Happy to help debug if I can somehow.

Yep, it's been stable here.

**Comment by samschott** [comment]
In that case, I'll close it :)

**Comment by schwerd** [comment]
I have continued to have crashes on both Sonoma and Ventura.  Not to the
frequency of the past, but still crashing.

I would argue that just claiming it’s done since no one is complaining, is
NOT justification to close the bug.   If the developer did NOTHING to find
and fix it, then you can’t claim it’s fixed.  Just because it hasn’t been
reported.  Bugs just don’t GO AWAY by themselves.

I’d like to hear what Sam found as a result of the bug reports and
crashlogs that he analyzed and what changes were made in the latest release
to address these crashes.

Only then, can one truly claim that a bug has been fixed.  Pretending it
hasn’t been reported does NOT mean it’s closed.

**Comment by schwerd** [comment]
agreed

bug seems to be less intrusive, but by no means fixed

**Comment by schwerd** [comment]
I hate to be the bearer of bad news, but as of today 12/27/2023, the app is crashing all the time now.  it only stays running for about 20 seconds and then crashes. relaunch, and it crashes again in about 20 seconds.  this has gone on for about 20 or 30 times today on two machines, both running Sonoma 14.2.1. not sure what is new. 

I'm happy to do anything I can for Sam to test or diagnose this. I don't know if it's related to volume of files attempting to sync.  today I moved a couple of large-ish folders into the sync folder and that's when I noticed it crashing on both machines.  

anyone else seeing this???  maybe if you have time, try a folder bigger than you usually sync to see if it is size related.

**Comment by schwerd** [comment]
Hope you’ve been able to read my most recent updates to the bug thread.

I’m at my wit’s end. App crashing within seconds of launching.

It appears that it continues to hang up when syncing 18/21.
Which makes me guess AGAIN that there is a specific file that it doesn’t
like and that causes the problems.
But since it doesn’t tell me what file it’s working on, I can’t manually
delete it or move it out of the sync folder or do something.

I run “maestral activity” and see a list of files that always show 0%
complete and I can’t tell if it’s working on things or not or what file
it’s working on.

I remotely log in to my other machine in my office and can see that changes
I’ve made at home on my laptop are NOT getting to the other machine.

If you could do a build that could output some more sync information to a
file that you could look at, or I could look at to see what’s causing this.

Since there doesn’t seem to be anything coming from the rest of your
community, I have to believe it’s something wrong with a file that I have.
But the app doesn’t help me figure out which one.

I really really really want to help.  Also, I’ve become completely
dependent on this app, so when you want to start charging a support fee,
I’m ready to support you.

Stephen
